### ISSUE TITLE
Cant create more than one POD

### ISSUE THREAD

**Issue by krupakar-code** [ganrad/Az-DevOps-Agent-On-AKS#2]
AZP_AGENT_NAME will be unique for each agent in a POOL.
If we are deploying two replicas only one will get created.The other pod will face an error "already has an active session exists"
Any possible to pass random name for AZP_AGENT_NAME?

**Comment by krupakar-code** [comment]
Just found a solution to dynamically take pod name as agent name
valueFrom:
            fieldRef:
              fieldPath: metadata.name

**Comment by ganrad** [comment]
@Krupakarreddin thanks for the feedback.  Updated the helm chart files.  Closing this issue. Thanks.

**Comment by ganrad** [comment]
@all-contributors please add @Krupakarreddin as bug identifier.  Thanks.
