### ISSUE TITLE
What is the purpose of ingress resource that is deployed

### ISSUE THREAD

**Issue by ghost** [ganrad/Az-DevOps-Agent-On-AKS#6]
Hi,

I just have question , what is the purpose of having ingress resource deployed for agent? 

End users will just consume agent in their pipeline in Azuredevops portal  and they will never hit the ingress. So had this question.

**Comment by ganrad** [comment]
Good question @kannappan199 .  The helm chart template files were auto generated using 'helm create' which is how the ingress resource got created.  You are right in that the devops agent does not use the ingress resource.  The ingress resource shouldn't get deployed on k8s either (ingress 'enabled' flag is set to false in 'values.yaml).  Hope this clarifies.  Thx.
