### ISSUE TITLE
Unable to Connect to kubernetes. What service connection do you use in devops to connect to my private cluster?

### ISSUE THREAD

**Issue by zimmerab** [ganrad/Az-DevOps-Agent-On-AKS#8]
I have a rbac cluster and I keep getting issues with my connections to use helm or kubectl in devops.

**Comment by ganrad** [comment]
@zimmerab You can create a service connection in ADO using one of the following - kubeconfig file, k8s service account or azure subscription.  Refer to the ADO docs.
